# Análisis exploratorio  de datos tabulados

In [61]:
#Vamos a importar pandas
import pandas as pd

In [62]:
#Vamos a leer los datos
#Para lo anterior definimos una variable
#Cada vez que vamos a leer un archivo con PANDAS, siempre se deben posicionar nuestros datos en la misma carpeta que estamos trabajando, si no, tendremos que copiar la dirección completa
df = pd.read_csv('Human_Resources.csv')
df
#Cuando lo veo se observan tres puntos en las filas y columnas, esto me indica que no me está mostrando todos

,Age,MonthlyIncome,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,Gender,HourlyRate,JobInvolvement,JobLevel,JobRole,JobSatisfaction,MaritalStatus,MonthlyRate,NumCompaniesWorked,Over18,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,5993.0,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1.0,2,Female,94,3,2,Sales Executive,4,Single,19479.0,8,Y,Yes,11.0,3.0,1,80,0,8,0,1,6,4,0,5
1,49,NaN,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2.0,3,Male,61,2,2,Research Scientist,2,Married,24907.0,1,Y,No,23.0,4.0,4,80,1,10,3,3,10,7,1,7
2,37,2090.0,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4.0,4,Male,92,2,1,Laboratory Technician,3,Single,2396.0,6,Y,Yes,15.0,3.0,2,80,0,7,3,3,0,0,0,0
3,33,2909.0,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5.0,4,Female,56,3,1,Research Scientist,3,Married,23159.0,1,Y,Yes,11.0,3.0,3,80,0,8,3,3,8,7,3,0
4,27,3468.0,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7.0,1,Male,40,3,1,Laboratory Technician,2,Married,16632.0,9,Y,No,12.0,3.0,4,80,1,6,3,3,2,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,36,2571.0,No,Travel_Frequently,884,Research & Development,23,2,Medical,1,2061.0,3,Male,41,4,2,Laboratory Technician,4,Married,12290.0,4,Y,No,17.0,3.0,3,80,1,17,3,3,5,2,0,3
1466,39,9991.0,No,Travel_Rarely,613,Research & Development,6,1,Medical,1,2062.0,4,Male,42,2,3,Healthcare Representative,1,Married,21457.0,4,Y,No,15.0,3.0,1,80,1,9,5,3,7,7,1,7
1467,27,6142.0,No,Travel_Rarely,155,Research & Development,4,3,Life Sciences,1,2064.0,2,Male,87,4,2,Manufacturing Director,2,Married,5174.0,1,Y,Yes,20.0,4.0,2,80,1,6,0,3,6,2,0,3
1468,49,5390.0,No,Travel_Frequently,1023,Sales,2,3,Medical,1,2065.0,4,Male,63,2,2,Sales Executive,2,Married,13243.0,2,Y,No,14.0,3.0,4,80,0,17,3,2,9,6,0,8
1469,34,4404.0,No,Travel_Rarely,628,Research & Development,8,3,Medical,1,2068.0,2,Male,82,4,2,Laboratory Technician,3,Married,10228.0,2,Y,No,12.0,3.0,1,80,0,6,3,4,4,3,1,2

In [63]:
type(df) #Así le preguntamos qué tipo  de datos es

pandas.core.frame.DataFrame

In [64]:
df.head(2) #Para que me muestre los primero dos elementos

,Age,MonthlyIncome,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,Gender,HourlyRate,JobInvolvement,JobLevel,JobRole,JobSatisfaction,MaritalStatus,MonthlyRate,NumCompaniesWorked,Over18,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,5993.0,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1.0,2,Female,94,3,2,Sales Executive,4,Single,19479.0,8,Y,Yes,11.0,3.0,1,80,0,8,0,1,6,4,0,5
1,49,NaN,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2.0,3,Male,61,2,2,Research Scientist,2,Married,24907.0,1,Y,No,23.0,4.0,4,80,1,10,3,3,10,7,1,7

In [65]:
#Para que me muestre los últimos dos elementos
df.tail(2)

,Age,MonthlyIncome,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,Gender,HourlyRate,JobInvolvement,JobLevel,JobRole,JobSatisfaction,MaritalStatus,MonthlyRate,NumCompaniesWorked,Over18,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
1468,49,5390.0,No,Travel_Frequently,1023,Sales,2,3,Medical,1,2065.0,4,Male,63,2,2,Sales Executive,2,Married,13243.0,2,Y,No,14.0,3.0,4,80,0,17,3,2,9,6,0,8
1469,34,4404.0,No,Travel_Rarely,628,Research & Development,8,3,Medical,1,2068.0,2,Male,82,4,2,Laboratory Technician,3,Married,10228.0,2,Y,No,12.0,3.0,1,80,0,6,3,4,4,3,1,2

In [66]:
#VOY A CONFIGURAR PARA QUE ME MUESTRE TODAS LAS COLUMNAS
pd.set_option('display.max_columns', None)
df

,Age,MonthlyIncome,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,Gender,HourlyRate,JobInvolvement,JobLevel,JobRole,JobSatisfaction,MaritalStatus,MonthlyRate,NumCompaniesWorked,Over18,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,5993.0,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1.0,2,Female,94,3,2,Sales Executive,4,Single,19479.0,8,Y,Yes,11.0,3.0,1,80,0,8,0,1,6,4,0,5
1,49,NaN,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2.0,3,Male,61,2,2,Research Scientist,2,Married,24907.0,1,Y,No,23.0,4.0,4,80,1,10,3,3,10,7,1,7
2,37,2090.0,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4.0,4,Male,92,2,1,Laboratory Technician,3,Single,2396.0,6,Y,Yes,15.0,3.0,2,80,0,7,3,3,0,0,0,0
3,33,2909.0,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5.0,4,Female,56,3,1,Research Scientist,3,Married,23159.0,1,Y,Yes,11.0,3.0,3,80,0,8,3,3,8,7,3,0
4,27,3468.0,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7.0,1,Male,40,3,1,Laboratory Technician,2,Married,16632.0,9,Y,No,12.0,3.0,4,80,1,6,3,3,2,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,36,2571.0,No,Travel_Frequently,884,Research & Development,23,2,Medical,1,2061.0,3,Male,41,4,2,Laboratory Technician,4,Married,12290.0,4,Y,No,17.0,3.0,3,80,1,17,3,3,5,2,0,3
1466,39,9991.0,No,Travel_Rarely,613,Research & Development,6,1,Medical,1,2062.0,4,Male,42,2,3,Healthcare Representative,1,Married,21457.0,4,Y,No,15.0,3.0,1,80,1,9,5,3,7,7,1,7
1467,27,6142.0,No,Travel_Rarely,155,Research & Development,4,3,Life Sciences,1,2064.0,2,Male,87,4,2,Manufacturing Director,2,Married,5174.0,1,Y,Yes,20.0,4.0,2,80,1,6,0,3,6,2,0,3
1468,49,5390.0,No,Travel_Frequently,1023,Sales,2,3,Medical,1,2065.0,4,Male,63,2,2,Sales Executive,2,Married,13243.0,2,Y,No,14.0,3.0,4,80,0,17,3,2,9,6,0,8
1469,34,4404.0,No,Travel_Rarely,628,Research & Development,8,3,Medical,1,2068.0,2,Male,82,4,2,Laboratory Technician,3,Married,10228.0,2,Y,No,12.0,3.0,1,80,0,6,3,4,4,3,1,2

In [67]:
#Mando a llamar las primeras 3
df.head(3)

,Age,MonthlyIncome,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,Gender,HourlyRate,JobInvolvement,JobLevel,JobRole,JobSatisfaction,MaritalStatus,MonthlyRate,NumCompaniesWorked,Over18,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,5993.0,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1.0,2,Female,94,3,2,Sales Executive,4,Single,19479.0,8,Y,Yes,11.0,3.0,1,80,0,8,0,1,6,4,0,5
1,49,NaN,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2.0,3,Male,61,2,2,Research Scientist,2,Married,24907.0,1,Y,No,23.0,4.0,4,80,1,10,3,3,10,7,1,7
2,37,2090.0,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4.0,4,Male,92,2,1,Laboratory Technician,3,Single,2396.0,6,Y,Yes,15.0,3.0,2,80,0,7,3,3,0,0,0,0

In [68]:
#mostramos la información que hay  de ésta tabla
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 35 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       1470 non-null   int64
 1   MonthlyIncome             1467 non-null   float64
 2   Attrition                 1470 non-null   object
 3   BusinessTravel            1470 non-null   object
 4   DailyRate                 1470 non-null   int64
 5   Department                1469 non-null   object
 6   DistanceFromHome          1470 non-null   int64
 7   Education                 1470 non-null   int64
 8   EducationField            1469 non-null   object
 9   EmployeeCount             1470 non-null   int64
 10  EmployeeNumber            1469 non-null   float64
 11  EnvironmentSatisfaction   1470 non-null   int64
 12  Gender                    1469 non-null   object
 13  HourlyRate                1470 non-null   int64
 14  JobInvolvement            1470 non-null   int64
 15  JobLevel                  1470 non-null   int64
 16  JobRole                   1469 non-null   object
 17  JobSatisfaction           1470 non-null   int64
 18  MaritalStatus             1469 non-null   object
 19  MonthlyRate               1468 non-null   float64
 20  NumCompaniesWorked        1470 non-null   int64
 21  Over18                    1470 non-null   object
 22  OverTime                  1470 non-null   object
 23  PercentSalaryHike         1469 non-null   float64
 24  PerformanceRating         1469 non-null   float64
 25  RelationshipSatisfaction  1470 non-null   int64
 26  StandardHours             1470 non-null   int64
 27  StockOptionLevel          1470 non-null   int64
 28  TotalWorkingYears         1470 non-null   int64
 29  TrainingTimesLastYear     1470 non-null   int64
 30  WorkLifeBalance           1470 non-null   int64
 31  YearsAtCompany            1470 non-null   int64
 32  YearsInCurrentRole        1470 non-null   int64
 33  YearsSinceLastPromotion   1470 non-null   int64
 34  YearsWithCurrManager      1470 non-null   int64
dtypes: float64(5), int64(21), object(9)
memory usage: 402.1+ KB

## IDENTIFICACIÓN DE VALORES ÚNICOS

In [69]:
#Con la siguiente función python me dice los valores que se repiten en una columa
#Lo anterior me puede servir para ver las categorías que hay
df[ 'Department'].unique()

array(['Sales', 'Research & Development', nan, 'Human Resources'],
      dtype=object)

In [70]:
#Lo de arriba lo puedo hacer con el año
df[ 'Age'].unique()

array([41, 49, 37, 33, 27, 32, 59, 30, 38, 36, 35, 29, 31, 34, 28, 22, 53,
       24, 21, 42, 44, 46, 39, 43, 50, 26, 48, 55, 45, 56, 23, 51, 40, 54,
       58, 20, 25, 19, 57, 52, 47, 18, 60])

In [71]:
#Variable rara de over 18
df[ 'Over18'].unique()
#Esta variable me indica si las personas son mayores de edad, aquí ya puedo descartar esta variable porque no me da gran información

array(['Y'], dtype=object)

In [72]:
#Vamos a ver OverTime
df[ 'OverTime'].unique()

array(['Yes', 'No'], dtype=object)

In [73]:
#Vamos por OverHome
df[ 'DistanceFromHome'].unique()

array([ 1,  8,  2,  3, 24, 23, 27, 16, 15, 26, 19, 21,  5, 11,  9,  7,  6,
       10,  4, 25, 12, 18, 29, 22, 14, 20, 28, 17, 13])

In [74]:
#SI YO QUISIERA HACERLA PARA TODAS EN LUGAR DE IR UNA POR UNA COMO ARRIBA
#Aquí sólo me dice cuántos elementos únicos hay en la columna
df.nunique()

Age                           43
MonthlyIncome               1346
Attrition                      2
BusinessTravel                 3
DailyRate                    886
Department                     3
DistanceFromHome              29
Education                      5
EducationField                 6
EmployeeCount                  1
EmployeeNumber              1469
EnvironmentSatisfaction        4
Gender                         2
HourlyRate                    71
JobInvolvement                 4
JobLevel                       5
JobRole                        9
JobSatisfaction                4
MaritalStatus                  3
MonthlyRate                 1425
NumCompaniesWorked            10
Over18                         1
OverTime                       2
PercentSalaryHike             15
PerformanceRating              2
RelationshipSatisfaction       4
StandardHours                  1
StockOptionLevel               4
TotalWorkingYears             40
TrainingTimesLastYear          7
WorkLifeBalance                4
YearsAtCompany                37
YearsInCurrentRole            19
YearsSinceLastPromotion       16
YearsWithCurrManager          18
dtype: int64

In [75]:
#Este comando me genera una lista de los nombres de las columnas en la tabla
df.columns.to_list()

['Age',
 'MonthlyIncome',
 'Attrition',
 'BusinessTravel',
 'DailyRate',
 'Department',
 'DistanceFromHome',
 'Education',
 'EducationField',
 'EmployeeCount',
 'EmployeeNumber',
 'EnvironmentSatisfaction',
 'Gender',
 'HourlyRate',
 'JobInvolvement',
 'JobLevel',
 'JobRole',
 'JobSatisfaction',
 'MaritalStatus',
 'MonthlyRate',
 'NumCompaniesWorked',
 'Over18',
 'OverTime',
 'PercentSalaryHike',
 'PerformanceRating',
 'RelationshipSatisfaction',
 'StandardHours',
 'StockOptionLevel',
 'TotalWorkingYears',
 'TrainingTimesLastYear',
 'WorkLifeBalance',
 'YearsAtCompany',
 'YearsInCurrentRole',
 'YearsSinceLastPromotion',
 'YearsWithCurrManager']

In [76]:
#Cómo imprimo los valores únicos?
for name in df.columns.to_list():
    print(f'La columna:{name} contiene los elementos {df[name ].unique()}')

La columna:Age contiene los elementos [41 49 37 33 27 32 59 30 38 36 35 29 31 34 28 22 53 24 21 42 44 46 39 43
 50 26 48 55 45 56 23 51 40 54 58 20 25 19 57 52 47 18 60]
La columna:MonthlyIncome contiene los elementos [5993.   nan 2090. ... 9991. 5390. 4404.]
La columna:Attrition contiene los elementos ['Yes' 'No']
La columna:BusinessTravel contiene los elementos ['Travel_Rarely' 'Travel_Frequently' 'Non-Travel']
La columna:DailyRate contiene los elementos [1102  279 1373 1392  591 1005 1324 1358  216 1299  809  153  670 1346
  103 1389  334 1123 1219  371  673 1218  419  391  699 1282 1125  691
  477  705  924 1459  125  895  813 1273  869  890  852 1141  464 1240
 1357  994  721 1360 1065  408 1211 1229  626 1434 1488 1097 1443  515
  853 1142  655 1115  427  653  989 1435 1223  836 1195 1339  664  318
 1225 1328 1082  548  132  746  776  193  397  945 1214  111  573 1153
 1400  541  432  288  669  530  632 1334  638 1093 1217 1353  120  682
  489  807  827  871  665 1040 1420  240 1280  534 1456  658  142 1127
 1031 1189 1354 1467  922  394 1312  750  441  684  249  841  147  528
  594  470  957  542  802 1355 1150 1329  959 1033 1316  364  438  689
  201 1427  857  933 1181 1395  662 1436  194  967 1496 1169 1145  630
  303 1256  440 1450 1452  465  702 1157  602 1480 1268  713  134  526
 1380  140  629 1356  328 1084  931  692 1069  313  894  556 1344  290
  138  926 1261  472 1002  878  905 1180  121 1136  635 1151  644 1045
  829 1242 1469  896  992 1052 1147 1396  663  119  979  319 1413  944
 1323  532  818  854 1034  771 1401 1431  976 1411 1300  252 1327  832
 1017 1199  504  505  916 1247  685  269 1416  833  307 1311  128  488
  529 1210 1463  675 1385 1403  452  666 1158  228  996  728 1315  322
 1479  797 1070  442  496 1372  920  688 1449 1117  636  506  444  950
  889  555  230 1232  566 1302  812 1476  218 1132 1105  906  849  390
  106 1249  192  553  117  185 1091  723 1220  588 1377 1018 1275  798
  672 1162  508 1482  559  210  928 1001  549 1124  738  570 1130 1192
  343  144 1296 1309  483  810  544 1062 1319  641 1332  756  845  593
 1171  350  921 1144  143 1046  575  156 1283  755  304 1178  329 1362
 1371  202  253  164 1107  759 1305  982  821 1381  480 1473  891 1063
  645 1490  317  422 1485 1368 1448  296 1398 1349  986 1099 1116 1499
  983 1009 1303 1274 1277  587  413 1276  988 1474  163  267  619  302
  443  828  561  426  232 1306 1094  509  775  195  258  471  799  956
  535 1495  446 1245  703  823 1246  622 1287  448  254 1365  538  525
  558  782  362 1236 1112  204 1343  604 1216  646  160  238 1397  306
  991  482 1176  913 1076  727  885  243  806  817 1410 1207 1442  693
  929  562  608  580  970 1179  294  314  316  654  168  381  217  501
  650  141  804  975 1090  346  430  268  167  621  527  883  954  310
  719  725  715  657 1146  182  376  571  384  791 1111 1243 1092 1325
  805  213  118  676 1252  286 1258  932 1041  859  720  946 1184  436
  589  760  887 1318  625  180  586 1012  661  930  342 1230 1271 1278
  607  130  300  583 1418 1269  379  395 1265 1222  341  868 1231  102
  881 1383 1075  374 1086  781  177  500 1425 1454  617 1085  995 1122
  618  546  462 1198 1272  154 1137 1188  188 1333  867  263  938  129
  616  498 1404 1053  289 1376  231  152  882  903 1379  335  722  461
  974 1126  840 1134  248  955  939 1391 1206  287 1441  109 1066  277
  466 1055  265  135  247 1035  266  145 1038 1234 1109 1089  788  124
  660 1186 1464  796  415  769 1003 1366  330 1492 1204  309 1330  469
  697 1262 1050  770  406  203 1308  984  439  793 1451 1182  174  490
  718  433  773  603  874  367  199  481  647 1384  902  819  862 1457
  977  942 1402 1421 1361  917  200  150  179  696  116  363  107 1465
  458 1212 1103  966 1010  326 1098  969 1167  694 1320  536  373  599
  251  131  237 1429  648  735  531  429  968  879  640  412  848  360
 1138  325 1322  299 1030  634  524  256 1060  935  495  282  206  943
  523  507  601  855 1291 1405 1369  999 1202  285  404  736 1498 1200
 1439  499  205  683 1462  949  652  332 1475  337  971 1174  667  560
  172  383 1255  359  401  377  592 1445 1221  866  981  447 1326  748
  990  405  115  790  830 1193 1423  467  271  410 1083  516  224  136
 1029  333 1440  674 1342  898  824  492  598  740  888 1288  104 1108
  479 1351  474  437  884 1370  264 1059  563  457 1313  241 1015  336
 1387  170  208  671  711  737 1470  365  763  567  486  772  301  311
  584  880  392  148  708 1259  786  370  678  146  581  918 1238  585
  741  552  369  717  543  964  792  611  176  897  600 1054  428  181
  211 1079  590  305  953  478 1375  244  511 1294  196  734 1239 1253
 1128 1336  234  766  261 1194  431  572 1422 1297  574  355  207  706
  280  726  414  352 1224  459 1254 1131  835 1172 1266  783  219 1213
 1096 1251 1394  605 1064 1337  937  157  754 1168  155 1444  189  911
 1321 1154  557  642  801  161 1382 1037  105  582  704  345 1120 1378
  468  613 1023  628]
La columna:Department contiene los elementos ['Sales' 'Research & Development' nan 'Human Resources']
La columna:DistanceFromHome contiene los elementos [ 1  8  2  3 24 23 27 16 15 26 19 21  5 11  9  7  6 10  4 25 12 18 29 22
 14 20 28 17 13]
La columna:Education contiene los elementos [2 1 4 3 5]
La columna:EducationField contiene los elementos ['Life Sciences' 'Other' 'Medical' nan 'Marketing' 'Technical Degree'
 'Human Resources']
La columna:EmployeeCount contiene los elementos [1]
La columna:EmployeeNumber contiene los elementos [1.000e+00 2.000e+00 4.000e+00 ... 2.064e+03 2.065e+03 2.068e+03]
La columna:EnvironmentSatisfaction contiene los elementos [2 3 4 1]
La columna:Gender contiene los elementos ['Female' 'Male' nan]
La columna:HourlyRate contiene los elementos [ 94  61  92  56  40  79  81  67  44  84  49  31  93  50  51  80  96  78
  45  82  53  83  58  72  48  42  41  86  97  75  33  37  73  98  36  47
  71  30  43  99  59  95  57  76  87  66  55  32  52  70  62  64  63  60
 100  46  39  77  35  91  54  34  90  65  88  85  89  68  69  74  38]
La columna:JobInvolvement contiene los elementos [3 2 4 1]
La columna:JobLevel contiene los elementos [2 1 3 4 5]
La columna:JobRole contiene los elementos ['Sales Executive' 'Research Scientist' 'Laboratory Technician' nan
 'Manufacturing Director' 'Healthcare Representative' 'Manager'
 'Sales Representative' 'Research Director' 'Human Resources']
La columna:JobSatisfaction contiene los elementos [4 2 3 1]
La columna:MaritalStatus contiene los elementos ['Single' 'Married' 'Divorced' nan]
La columna:MonthlyRate contiene los elementos [19479. 24907.  2396. ...  5174. 13243. 10228.]
La columna:NumCompaniesWorked contiene los elementos [8 1 6 9 0 4 5 2 7 3]
La columna:Over18 contiene los elementos ['Y']
La columna:OverTime contiene los elementos ['Yes' 'No']
La columna:PercentSalaryHike contiene los elementos [11. 23. 15. 12. 13. nan 22. 21. 17. 14. 16. 18. 19. 20. 24. 25.]
La columna:PerformanceRating contiene los elementos [ 3.  4. nan]
La columna:RelationshipSatisfaction contiene los elementos [1 4 2 3]
La columna:StandardHours contiene los elementos [80]
La columna:StockOptionLevel contiene los elementos [0 1 3 2]
La columna:TotalWorkingYears contiene los elementos [ 8 10  7  6 12  1 17  5  3 31 13  0 26 24 22  9 19  2 23 14 15  4 29 28
 21 25 20 11 16 37 38 30 40 18 36 34 32 33 35 27]
La columna:TrainingTimesLastYear contiene los elementos [0 3 2 5 1 4 6]
La columna:WorkLifeBalance contiene los elementos [1 3 2 4]
La columna:YearsAtCompany contiene los elementos [ 6 10  0  8  2  7  1  9  5  4 25  3 12 14 22 15 27 21 17 11 13 37 16 20
 40 24 33 19 36 18 29 31 32 34 26 30 23]
La columna:YearsInCurrentRole contiene los elementos [ 4  7  0  2  5  9  8  3  6 13  1 15 14 16 11 10 12 18 17]
La columna:YearsSinceLastPromotion contiene los elementos [ 0  1  3  2  7  4  8  6  5 15  9 13 12 10 11 14]
La columna:YearsWithCurrManager contiene los elementos [ 5  7  0  2  6  8  3 11 17  1  4 12  9 10 15 13 16 14]

In [77]:
#Ahora vamos a eliminar las variables que no me van a brindar información en mi modelo
valores_unicos_n = df.nunique() #Le digo que haga un conteo y lo meta en la variable en forma de serie
#De la serie de valores_unicos_n vamos a extraer los que tienen valores únicos
columnas_sin_info = valores_unicos_n[valores_unicos_n==1 ].index.tolist() #Aquí le digo que si es igual a 1, entonces me los indique, le ponemos index.list para que me devuelva sólo las variables en forma de lista y las etiqeutas
columnas_sin_info

['EmployeeCount', 'Over18', 'StandardHours']

In [78]:
#Ahora vamos a eliminar esas columnas
#.drop es el comando que se usa para eliminar filas o columnas
# df.drop(columnas_sin_info, axis = 1, inplace=True)   esta es la manera para que se reemplace
df_clean= df.drop(columnas_sin_info, axis = 1) #Le pongo axis = 1 porque son columnas y inplace = True para que los reemplaze sin necesidad de reasignarlo a una variable
#La de arriba es para que se reemplace en una variable

In [79]:
df_clean.head(3)

,Age,MonthlyIncome,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeNumber,EnvironmentSatisfaction,Gender,HourlyRate,JobInvolvement,JobLevel,JobRole,JobSatisfaction,MaritalStatus,MonthlyRate,NumCompaniesWorked,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,5993.0,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1.0,2,Female,94,3,2,Sales Executive,4,Single,19479.0,8,Yes,11.0,3.0,1,0,8,0,1,6,4,0,5
1,49,NaN,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,2.0,3,Male,61,2,2,Research Scientist,2,Married,24907.0,1,No,23.0,4.0,4,1,10,3,3,10,7,1,7
2,37,2090.0,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,4.0,4,Male,92,2,1,Laboratory Technician,3,Single,2396.0,6,Yes,15.0,3.0,2,0,7,3,3,0,0,0,0

In [80]:
df_clean.describe() #Obtiene un resumen estadístico, es importante resaltar que la variable describe excluye los valores nulos, por eso en el conteo no sale igual
#Se observa que python reconoce como variable numérica a las cualitativas, por ello les saca sus valores

,Age,MonthlyIncome,DailyRate,DistanceFromHome,Education,EmployeeNumber,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,JobSatisfaction,MonthlyRate,NumCompaniesWorked,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
count,1470.000000,1467.000000,1470.000000,1470.000000,1470.000000,1469.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1468.000000,1470.000000,1469.000000,1469.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000
mean,36.923810,6505.155419,802.485714,9.192517,2.912925,1025.556161,2.721769,65.891156,2.729932,2.063946,2.728571,14310.966621,2.693197,15.206263,3.153165,2.712245,0.793878,11.279592,2.799320,2.761224,7.008163,4.229252,2.187755,4.123129
std,9.135373,4711.297846,403.509100,8.106864,1.024165,601.646166,1.093082,20.329428,0.711561,1.106940,1.102846,7121.294449,2.498009,3.659047,0.360270,1.081209,0.852077,7.780782,1.289271,0.706476,6.126525,3.623137,3.222430,3.568136
min,18.000000,1009.000000,102.000000,1.000000,1.000000,1.000000,1.000000,30.000000,1.000000,1.000000,1.000000,2094.000000,0.000000,11.000000,3.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,30.000000,2911.000000,465.000000,2.000000,2.000000,492.000000,2.000000,48.000000,2.000000,1.000000,2.000000,8043.750000,1.000000,12.000000,3.000000,2.000000,0.000000,6.000000,2.000000,2.000000,3.000000,2.000000,0.000000,2.000000
50%,36.000000,4908.000000,802.000000,7.000000,3.000000,1022.000000,3.000000,66.000000,3.000000,2.000000,3.000000,14235.500000,2.000000,14.000000,3.000000,3.000000,1.000000,10.000000,3.000000,3.000000,5.000000,3.000000,1.000000,3.000000
75%,43.000000,8378.000000,1157.000000,14.000000,4.000000,1556.000000,4.000000,83.750000,3.000000,3.000000,4.000000,20463.250000,4.000000,18.000000,3.000000,4.000000,1.000000,15.000000,3.000000,3.000000,9.000000,7.000000,3.000000,7.000000
max,60.000000,19999.000000,1499.000000,29.000000,5.000000,2068.000000,4.000000,100.000000,4.000000,5.000000,4.000000,26999.000000,9.000000,25.000000,4.000000,4.000000,3.000000,40.000000,6.000000,4.000000,40.000000,18.000000,15.000000,17.000000

## DIVISIÓN DE UN DATASET

In [84]:
#Creamos nueva variable de las personas que siguen trabajando
siguen_trabajando = df_clean[df_clean ['Attrition' ]== 'No']
siguen_trabajando
#Co unique checamos si el data set es unico
siguen_trabajando ['Attrition' ].unique()

array(['No'], dtype=object)

In [89]:

#Ahora cremos un nuevo data set
renunciaron = df_clean[df_clean ['Attrition' ] =='Yes']
renunciaron

,Age,MonthlyIncome,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeNumber,EnvironmentSatisfaction,Gender,HourlyRate,JobInvolvement,JobLevel,JobRole,JobSatisfaction,MaritalStatus,MonthlyRate,NumCompaniesWorked,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,5993.0,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1.0,2,Female,94,3,2,Sales Executive,4,Single,19479.0,8,Yes,11.0,3.0,1,0,8,0,1,6,4,0,5
2,37,2090.0,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,4.0,4,Male,92,2,1,Laboratory Technician,3,Single,2396.0,6,Yes,15.0,3.0,2,0,7,3,3,0,0,0,0
14,28,2028.0,Yes,Travel_Rarely,103,Research & Development,24,3,Life Sciences,19.0,3,Male,50,2,1,Laboratory Technician,3,Single,12947.0,5,Yes,14.0,3.0,2,0,6,4,3,4,2,0,3
21,36,3407.0,Yes,Travel_Rarely,1218,Sales,9,4,Life Sciences,27.0,3,Male,82,2,1,Sales Representative,1,Single,6986.0,7,No,23.0,4.0,2,0,10,4,3,5,3,0,3
24,34,2960.0,Yes,Travel_Rarely,699,Research & Development,6,1,Medical,31.0,2,Male,83,3,1,Research Scientist,1,Single,17102.0,2,No,11.0,3.0,3,0,8,2,3,4,2,1,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1438,23,1790.0,Yes,Travel_Frequently,638,Sales,9,3,Marketing,2023.0,4,Male,33,3,1,Sales Representative,1,Married,26956.0,1,No,19.0,3.0,1,1,1,3,2,1,0,1,0
1442,29,4787.0,Yes,Travel_Rarely,1092,Research & Development,1,4,Medical,2027.0,1,Male,36,3,1,Research Scientist,4,Married,26124.0,9,Yes,14.0,3.0,2,3,4,3,4,2,2,2,2
1444,56,2339.0,Yes,Travel_Rarely,310,Research & Development,7,2,Technical Degree,2032.0,4,Male,72,3,1,Laboratory Technician,3,Married,3666.0,8,No,11.0,3.0,4,1,14,4,1,10,9,9,8
1452,50,6728.0,Yes,Travel_Frequently,878,Sales,1,4,Life Sciences,2044.0,2,Male,94,3,2,Sales Executive,3,Divorced,14255.0,7,No,12.0,3.0,4,2,12,3,3,6,3,0,1
1461,50,10854.0,Yes,Travel_Rarely,410,Sales,28,3,Marketing,2055.0,4,Male,39,2,3,Sales Executive,1,Divorced,16586.0,4,Yes,13.0,3.0,2,1,20,3,3,3,2,2,0

In [90]:
renunciaron.describe()

,Age,MonthlyIncome,DailyRate,DistanceFromHome,Education,EmployeeNumber,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,JobSatisfaction,MonthlyRate,NumCompaniesWorked,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
count,237.000000,236.000000,237.000000,237.000000,237.000000,237.000000,237.000000,237.000000,237.000000,237.000000,237.000000,237.000000,237.000000,237.000000,237.000000,237.000000,237.000000,237.000000,237.000000,237.000000,237.000000,237.000000,237.000000,237.000000
mean,33.607595,4771.588983,750.362869,10.632911,2.839662,1010.345992,2.464135,65.573840,2.518987,1.637131,2.468354,14559.308017,2.940928,15.097046,3.156118,2.599156,0.527426,8.244726,2.624473,2.658228,5.130802,2.902954,1.945148,2.852321
std,9.689350,3640.097444,401.899519,8.452525,1.008244,580.750572,1.169791,20.099958,0.773405,0.940594,1.118058,7208.153264,2.678519,3.770294,0.363735,1.125437,0.856361,7.169204,1.254784,0.816453,5.949984,3.174827,3.153077,3.143349
min,18.000000,1009.000000,103.000000,1.000000,1.000000,1.000000,1.000000,31.000000,1.000000,1.000000,1.000000,2326.000000,0.000000,11.000000,3.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,28.000000,2371.500000,408.000000,3.000000,2.000000,514.000000,1.000000,50.000000,2.000000,1.000000,1.000000,8870.000000,1.000000,12.000000,3.000000,2.000000,0.000000,3.000000,2.000000,2.000000,1.000000,0.000000,0.000000,0.000000
50%,32.000000,3187.000000,699.000000,9.000000,3.000000,1017.000000,3.000000,66.000000,3.000000,1.000000,3.000000,14618.000000,1.000000,14.000000,3.000000,3.000000,0.000000,7.000000,2.000000,3.000000,3.000000,2.000000,1.000000,2.000000
75%,39.000000,5850.000000,1092.000000,17.000000,4.000000,1486.000000,4.000000,84.000000,3.000000,2.000000,3.000000,21081.000000,5.000000,17.000000,3.000000,4.000000,1.000000,10.000000,3.000000,3.000000,7.000000,4.000000,2.000000,5.000000
max,58.000000,19859.000000,1496.000000,29.000000,5.000000,2055.000000,4.000000,100.000000,4.000000,5.000000,4.000000,26999.000000,9.000000,25.000000,4.000000,4.000000,3.000000,40.000000,6.000000,4.000000,40.000000,15.000000,15.000000,14.000000

In [91]:
siguen_trabajando.describe()

,Age,MonthlyIncome,DailyRate,DistanceFromHome,Education,EmployeeNumber,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,JobSatisfaction,MonthlyRate,NumCompaniesWorked,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
count,1233.000000,1231.000000,1233.000000,1233.000000,1233.000000,1232.000000,1233.000000,1233.000000,1233.000000,1233.000000,1233.000000,1231.000000,1233.00000,1232.000000,1232.000000,1233.000000,1233.000000,1233.000000,1233.000000,1233.000000,1233.000000,1233.000000,1233.000000,1233.000000
mean,37.561233,6837.504468,812.504461,8.915653,2.927007,1028.482143,2.771290,65.952149,2.770479,2.145985,2.778589,14263.154346,2.64558,15.227273,3.152597,2.733982,0.845093,11.862936,2.832928,2.781022,7.369019,4.484185,2.234388,4.367397
std,8.888360,4820.415800,403.208379,8.012633,1.027002,605.768693,1.071132,20.380754,0.692050,1.117933,1.093277,7106.411508,2.46009,3.638449,0.359745,1.071603,0.841985,7.760719,1.293585,0.681907,6.096298,3.649402,3.234762,3.594116
min,18.000000,1051.000000,102.000000,1.000000,1.000000,2.000000,1.000000,30.000000,1.000000,1.000000,1.000000,2094.000000,0.00000,11.000000,3.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,31.000000,3211.500000,477.000000,2.000000,2.000000,483.750000,2.000000,48.000000,2.000000,1.000000,2.000000,7961.500000,1.00000,12.000000,3.000000,2.000000,0.000000,6.000000,2.000000,2.000000,3.000000,2.000000,0.000000,2.000000
50%,36.000000,5206.000000,817.000000,7.000000,3.000000,1023.000000,3.000000,66.000000,3.000000,2.000000,3.000000,14120.000000,2.00000,14.000000,3.000000,3.000000,1.000000,10.000000,3.000000,3.000000,6.000000,3.000000,1.000000,3.000000
75%,43.000000,8835.500000,1176.000000,13.000000,4.000000,1574.500000,4.000000,83.000000,3.000000,3.000000,4.000000,20378.000000,4.00000,18.000000,3.000000,4.000000,1.000000,16.000000,3.000000,3.000000,10.000000,7.000000,3.000000,7.000000
max,60.000000,19999.000000,1499.000000,29.000000,5.000000,2068.000000,4.000000,100.000000,4.000000,5.000000,4.000000,26997.000000,9.00000,25.000000,4.000000,4.000000,3.000000,38.000000,6.000000,4.000000,37.000000,18.000000,15.000000,17.000000

EN LO  DE ARRIBA ESTAMOS VIENDO PORQUÉ RENUNCIARON O MÁS BIEN, CUÁNTOS RENUNCIARON

In [97]:
personas_sueldo_bien = siguen_trabajando[(siguen_trabajando['MonthlyIncome' ] >10000) & (siguen_trabajando['MonthlyIncome' ] <15000) ] #ESTA CONDICIÓN NOS LIMITA A LAS PERSONAS QUE GANAN ENTRE 10000 O 150000
personas_sueldo_bien.describe()

,Age,MonthlyIncome,DailyRate,DistanceFromHome,Education,EmployeeNumber,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,JobSatisfaction,MonthlyRate,NumCompaniesWorked,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
count,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000
mean,44.132812,12018.539062,796.640625,10.070312,2.968750,974.875000,2.703125,66.476562,2.648438,3.289062,2.742188,15510.437500,3.437500,15.546875,3.179688,2.773438,0.890625,20.195312,2.960938,2.835938,11.578125,6.578125,4.054688,5.945312
std,8.368831,1442.897538,404.609323,8.707119,1.011256,568.290349,1.037558,18.502166,0.694068,0.455108,1.066646,7099.560896,2.604509,3.954185,0.385436,0.973789,0.805829,6.970194,1.394039,0.718456,7.726230,4.208371,4.658932,4.289354
min,27.000000,10096.000000,102.000000,1.000000,1.000000,28.000000,1.000000,30.000000,1.000000,3.000000,1.000000,2094.000000,0.000000,11.000000,3.000000,1.000000,0.000000,9.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,38.000000,10685.750000,474.250000,3.000000,2.000000,497.000000,2.000000,52.750000,2.000000,3.000000,2.000000,9223.500000,1.000000,12.000000,3.000000,2.000000,0.000000,15.000000,2.000000,3.000000,5.000000,3.000000,0.000000,2.000000
50%,44.000000,11774.500000,798.500000,7.000000,3.000000,1006.000000,3.000000,67.500000,3.000000,3.000000,3.000000,15709.000000,3.000000,14.000000,3.000000,3.000000,1.000000,20.000000,3.000000,3.000000,10.000000,7.000000,2.000000,7.000000
75%,51.000000,13459.500000,1104.500000,17.000000,4.000000,1398.000000,3.000000,81.000000,3.000000,4.000000,4.000000,21127.250000,5.000000,18.000000,3.000000,4.000000,1.000000,24.000000,3.000000,3.000000,17.000000,9.000000,6.250000,9.000000
max,60.000000,14852.000000,1499.000000,29.000000,5.000000,2056.000000,4.000000,100.000000,4.000000,4.000000,4.000000,26862.000000,9.000000,25.000000,4.000000,4.000000,3.000000,38.000000,6.000000,4.000000,37.000000,17.000000,15.000000,17.000000

In [98]:
personas_sueldo_bien_distancia = siguen_trabajando[(siguen_trabajando['MonthlyIncome' ] >10000) & (siguen_trabajando['DistanceFromHome' ] >8) ] #Filtro para los que ganen más de 10000 y viven a mas de 8 km. Operador & (and)
personas_sueldo_bien_distancia.describe()

,Age,MonthlyIncome,DailyRate,DistanceFromHome,Education,EmployeeNumber,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,JobSatisfaction,MonthlyRate,NumCompaniesWorked,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
count,93.000000,93.000000,93.000000,93.000000,93.000000,93.000000,93.000000,93.000000,93.000000,93.000000,93.000000,93.000000,93.000000,93.000000,93.000000,93.000000,93.000000,93.000000,93.000000,93.000000,93.000000,93.00000,93.000000,93.000000
mean,45.225806,14717.795699,809.290323,18.204301,3.150538,1107.795699,2.838710,70.053763,2.709677,3.827957,2.688172,14658.161290,3.172043,15.806452,3.236559,2.741935,0.763441,22.483871,2.731183,2.903226,12.774194,6.72043,3.860215,6.010753
std,7.348660,3190.457213,421.171750,6.940053,0.988480,555.774617,1.066183,18.865292,0.668884,0.716629,1.103143,7551.183851,2.258432,4.299287,0.427273,0.954432,0.713196,6.837577,1.368431,0.590956,8.863860,4.37971,4.564969,4.583749
min,30.000000,10266.000000,102.000000,9.000000,1.000000,131.000000,1.000000,30.000000,1.000000,3.000000,1.000000,2125.000000,0.000000,11.000000,3.000000,1.000000,0.000000,9.000000,0.000000,1.000000,0.000000,0.00000,0.000000,0.000000
25%,40.000000,11510.000000,458.000000,11.000000,3.000000,597.000000,2.000000,58.000000,2.000000,3.000000,2.000000,7914.000000,1.000000,12.000000,3.000000,2.000000,0.000000,18.000000,2.000000,3.000000,5.000000,3.00000,0.000000,2.000000
50%,45.000000,13973.000000,829.000000,18.000000,3.000000,1092.000000,3.000000,72.000000,3.000000,4.000000,3.000000,14864.000000,3.000000,14.000000,3.000000,3.000000,1.000000,22.000000,2.000000,3.000000,11.000000,7.00000,2.000000,7.000000
75%,50.000000,17181.000000,1176.000000,25.000000,4.000000,1578.000000,4.000000,87.000000,3.000000,4.000000,4.000000,20689.000000,4.000000,18.000000,3.000000,3.000000,1.000000,27.000000,3.000000,3.000000,20.000000,10.00000,6.000000,9.000000
max,60.000000,19926.000000,1499.000000,29.000000,5.000000,2056.000000,4.000000,100.000000,4.000000,5.000000,4.000000,26862.000000,9.000000,25.000000,4.000000,4.000000,3.000000,38.000000,6.000000,4.000000,37.000000,17.00000,15.000000,17.000000

In [99]:
#También puedp filtrar para las personas que ganen mas de 10000 o vivan a 8 km
personas_sueldo_bien_odistancia = siguen_trabajando[(siguen_trabajando['MonthlyIncome' ] >10000) | (siguen_trabajando['DistanceFromHome' ] >8) ] #Filtro para los que ganen más de 10000 o viven a mas de 8 km, el operador es | (operador or)
personas_sueldo_bien_odistancia.describe()

,Age,MonthlyIncome,DailyRate,DistanceFromHome,Education,EmployeeNumber,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,JobSatisfaction,MonthlyRate,NumCompaniesWorked,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
count,656.000000,656.000000,656.000000,656.000000,656.000000,656.000000,656.000000,656.000000,656.000000,656.000000,656.000000,655.000000,656.000000,656.000000,656.000000,656.000000,656.000000,656.000000,656.00000,656.000000,656.000000,656.000000,656.000000,656.000000
mean,39.425305,8735.211890,812.059451,13.629573,2.964939,1032.387195,2.760671,66.393293,2.769817,2.565549,2.783537,14537.082443,2.809451,15.239329,3.149390,2.756098,0.879573,14.353659,2.83689,2.775915,8.646341,4.974085,2.731707,4.842988
std,9.308483,5672.922517,406.162459,8.247043,1.011532,601.065786,1.062494,20.308857,0.663374,1.271641,1.080897,7157.881635,2.523532,3.703810,0.356745,1.052061,0.824701,8.791213,1.29800,0.692445,7.126978,3.875261,3.740592,3.878858
min,18.000000,1052.000000,102.000000,1.000000,1.000000,11.000000,1.000000,30.000000,1.000000,1.000000,1.000000,2094.000000,0.000000,11.000000,3.000000,1.000000,0.000000,0.000000,0.00000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,33.000000,4013.250000,469.000000,9.000000,2.000000,503.750000,2.000000,49.000000,2.000000,2.000000,2.000000,8267.000000,1.000000,12.000000,3.000000,2.000000,0.000000,8.000000,2.00000,2.000000,4.000000,2.000000,0.000000,2.000000
50%,39.000000,6558.000000,803.000000,11.000000,3.000000,1041.000000,3.000000,67.000000,3.000000,2.000000,3.000000,14408.000000,2.000000,14.000000,3.000000,3.000000,1.000000,11.000000,3.00000,3.000000,7.000000,4.000000,1.000000,4.000000
75%,46.000000,13325.250000,1179.250000,20.000000,4.000000,1564.250000,4.000000,83.250000,3.000000,4.000000,4.000000,21021.000000,4.000000,18.000000,3.000000,4.000000,1.000000,21.000000,3.00000,3.000000,10.000000,7.000000,4.000000,7.000000
max,60.000000,19999.000000,1499.000000,29.000000,5.000000,2061.000000,4.000000,100.000000,4.000000,5.000000,4.000000,26968.000000,9.000000,25.000000,4.000000,4.000000,3.000000,38.000000,6.00000,4.000000,37.000000,18.000000,15.000000,17.000000

In [100]:
personas_sueldo_bien_ydistancia_ysatisfecho = siguen_trabajando[(siguen_trabajando['MonthlyIncome' ] >10000) & (siguen_trabajando['EnvironmentSatisfaction' ] ==4) & (siguen_trabajando[ 'DistanceFromHome']>8) ] #Filtro para los que ganen más de 10000 y estén satisfechos con el trabajo y viven a 8 km
personas_sueldo_bien_ydistancia_ysatisfecho.describe()

,Age,MonthlyIncome,DailyRate,DistanceFromHome,Education,EmployeeNumber,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,JobSatisfaction,MonthlyRate,NumCompaniesWorked,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
count,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.0,31.000000,31.000000,31.00000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000
mean,47.096774,15489.096774,850.935484,18.064516,3.032258,1151.193548,4.0,68.612903,2.774194,4.00000,2.741935,14303.548387,3.354839,14.483871,3.129032,2.709677,0.612903,24.225806,2.387097,2.806452,12.838710,6.903226,3.870968,5.967742
std,6.759462,3221.786134,450.191066,7.252289,0.706346,532.564889,0.0,20.668297,0.616964,0.68313,1.153769,7501.175156,1.817478,3.713677,0.340777,0.937854,0.667204,5.707946,1.308368,0.542792,9.241561,4.770429,4.514731,4.370232
min,33.000000,10496.000000,102.000000,9.000000,2.000000,131.000000,4.0,30.000000,2.000000,3.00000,1.000000,2125.000000,0.000000,11.000000,3.000000,1.000000,0.000000,10.000000,0.000000,2.000000,1.000000,0.000000,0.000000,0.000000
25%,43.500000,13258.000000,606.000000,10.000000,3.000000,889.500000,4.0,52.500000,2.000000,4.00000,2.000000,8436.500000,2.000000,12.000000,3.000000,2.000000,0.000000,21.000000,2.000000,2.500000,5.000000,3.000000,1.000000,2.500000
50%,48.000000,16328.000000,939.000000,18.000000,3.000000,1217.000000,4.0,72.000000,3.000000,4.00000,3.000000,13871.000000,3.000000,13.000000,3.000000,3.000000,1.000000,24.000000,2.000000,3.000000,12.000000,6.000000,1.000000,6.000000
75%,51.000000,17762.500000,1229.000000,24.500000,3.000000,1559.000000,4.0,85.000000,3.000000,4.00000,4.000000,20347.500000,4.000000,16.500000,3.000000,3.000000,1.000000,28.000000,3.000000,3.000000,19.500000,10.000000,5.500000,9.000000
max,59.000000,19847.000000,1450.000000,28.000000,5.000000,2022.000000,4.0,100.000000,4.000000,5.00000,4.000000,26362.000000,8.000000,24.000000,4.000000,4.000000,3.000000,38.000000,6.000000,4.000000,37.000000,17.000000,15.000000,17.000000

In [101]:
personas_sueldo_bien_ydistancia_ysatisfecho.head()

,Age,MonthlyIncome,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeNumber,EnvironmentSatisfaction,Gender,HourlyRate,JobInvolvement,JobLevel,JobRole,JobSatisfaction,MaritalStatus,MonthlyRate,NumCompaniesWorked,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
98,58,13872.0,No,Travel_Rarely,682,Sales,10,4,Medical,131.0,4,Male,37,3,4,Sales Executive,3,Single,24409.0,0,No,13.0,3.0,3,0,38,1,2,37,10,1,8
112,54,17328.0,No,Non-Travel,142,Human Resources,26,3,Human Resources,148.0,4,Female,30,4,4,Manager,4,Single,13871.0,2,Yes,12.0,3.0,3,0,23,3,3,5,3,4,4
147,41,17181.0,No,Travel_Frequently,857,Research & Development,10,3,Life Sciences,199.0,4,Male,91,2,4,Manager,1,Divorced,12888.0,4,No,13.0,3.0,2,1,21,2,2,7,6,7,7
235,43,16064.0,No,Travel_Rarely,1034,Sales,16,3,Marketing,327.0,4,Female,80,3,4,Manager,4,Married,7744.0,5,Yes,22.0,4.0,3,1,22,3,3,17,13,1,9
367,50,10496.0,No,Travel_Rarely,1046,Research & Development,10,3,Technical Degree,491.0,4,Male,100,2,3,Healthcare Representative,4,Single,2755.0,6,No,15.0,3.0,4,0,20,2,3,4,3,1,3

In [102]:
#Si yo quiero ver qué rol cumplen los que filtré arriba
personas_sueldo_bien_ydistancia_ysatisfecho['JobRole' ].unique() #Recordar que unique me indica valores únicos

array(['Sales Executive', 'Manager', 'Healthcare Representative',
       'Research Director', 'Manufacturing Director'], dtype=object)

In [103]:
personas_sueldo_bien_ydistancia_ysatisfecho[ personas_sueldo_bien_ydistancia_ysatisfecho['JobRole' ]=='Sales Executive'].describe()
#Aquí quiero que me diga con el describe cuántos tiene el cargo de Sales Executive y en promedio cuánto ganan

,Age,MonthlyIncome,DailyRate,DistanceFromHome,Education,EmployeeNumber,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,JobSatisfaction,MonthlyRate,NumCompaniesWorked,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
count,3.00000,3.000000,3.000000,3.000000,3.000000,3.000000,3.0,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.0,3.0,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000
mean,49.00000,12651.000000,1020.000000,15.666667,3.333333,678.000000,4.0,54.666667,3.333333,3.666667,2.666667,18461.666667,2.333333,14.333333,3.0,3.0,0.666667,26.333333,1.666667,2.666667,18.000000,8.333333,4.000000,7.000000
std,7.81025,1659.894876,390.850355,10.692677,0.577350,481.729177,0.0,18.556221,0.577350,0.577350,1.527525,6371.662368,2.081666,3.214550,0.0,0.0,0.577350,10.408330,0.577350,0.577350,16.822604,3.785939,6.082763,4.582576
min,44.00000,10761.000000,682.000000,9.000000,3.000000,131.000000,4.0,37.000000,3.000000,3.000000,1.000000,11737.000000,0.000000,12.000000,3.0,3.0,0.000000,18.000000,1.000000,2.000000,5.000000,4.000000,0.000000,2.000000
25%,44.50000,12040.500000,806.000000,9.500000,3.000000,497.500000,4.0,45.000000,3.000000,3.500000,2.000000,15488.000000,1.500000,12.500000,3.0,3.0,0.500000,20.500000,1.500000,2.500000,8.500000,7.000000,0.500000,5.000000
50%,45.00000,13320.000000,930.000000,10.000000,3.000000,864.000000,4.0,53.000000,3.000000,4.000000,3.000000,19239.000000,3.000000,13.000000,3.0,3.0,1.000000,23.000000,2.000000,3.000000,12.000000,10.000000,1.000000,8.000000
75%,51.50000,13596.000000,1189.000000,19.000000,3.500000,951.500000,4.0,63.500000,3.500000,4.000000,3.500000,21824.000000,3.500000,15.500000,3.0,3.0,1.000000,30.500000,2.000000,3.000000,24.500000,10.500000,6.000000,9.500000
max,58.00000,13872.000000,1448.000000,28.000000,4.000000,1039.000000,4.0,74.000000,4.000000,4.000000,4.000000,24409.000000,4.000000,18.000000,3.0,3.0,1.000000,38.000000,2.000000,3.000000,37.000000,11.000000,11.000000,11.000000

Al final de nuestro análisis exploratorio podemos escribir algún tipo de conclusión con lo que hemos hecho

Hablando de fuentes de datos podemos utilizar las siguientes:
kaggle: es una plataforma que nos puede dar bases de datos tanto procesados como crudos
HAY OTRA PAGINA LLAMADA UCI MACHINE LEARNING REPOSITORY
PARA MEXICO HAY LA PAGINA DATOS ABIERTOS DE MEXICO